apiVersion: v1
kind: Service
metadata:
  name: saba-express-app-service
spec:
  selector:
    app: saba-express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer